version: "3"
services:
  mock-json-server:
    image: halverneus/static-file-server
    networks:
      - streaming-data-internal
    ports:
      - 8080:8080
    volumes:
      - ./data:/web

  station-san-francisco-producer:
    build:
      context: ../CitibikeApiProducer
      dockerfile: Dockerfile-station-san-francisco
    depends_on:
      - kafka
      - zookeeper-seed
    networks:
      - streaming-data-internal
    environment:
      - PRODUCER_URL=http://mock-json-server:8080/mock_station_data_sf.json
      - PRODUCER_CRON=*/3 * * * * *

  station-marseille-producer:
    build:
      context: ../CitibikeApiProducer
      dockerfile: Dockerfile-station-marseille
    depends_on:
      - kafka
      - zookeeper-seed
    networks:
      - streaming-data-internal
    environment:
      - PRODUCER_URL=http://mock-json-server:8080/mock_station_data_marseille.json
      - PRODUCER_CRON=*/3 * * * * *

  station-nyc-v2-producer:
    build:
      context: ../CitibikeApiProducer
      dockerfile: Dockerfile-station-nyc-v2
    depends_on:
      - kafka
      - zookeeper-seed
    networks:
      - streaming-data-internal
    environment:
      - PRODUCER_URL=http://mock-json-server:8080/mock_station_data_nyc_v2.json
      - PRODUCER_CRON=*/3 * * * * *

  kafka:
    volumes:
      - ./data:/tmp
