version: "3"
services:

  zookeeper-seed:
    build:
      context: ../zookeeper
    networks:
      - streaming-data-internal
    depends_on:
      - zookeeper
    volumes:
      - ../zookeeper/e2e-seed.sh:/e2e-seed.sh
    command: [ "sh", "/e2e-seed.sh" ]

  station-information-producer:
    build:
      context: ../CitibikeApiProducer
      dockerfile: Dockerfile-station-information
    depends_on:
      - kafka
      - zookeeper-seed
    networks:
      - streaming-data-internal
    environment:
      - PRODUCER_URL=https://gbfs.citibikenyc.com/gbfs/en/station_information.json
      - PRODUCER_TOPIC=e2e_station_information
      - PRODUCER_PRODUCERID=e2e_producer_station_information
      - PRODUCER_CRON=*/3 * * * * *

  station-status-producer:
    build:
      context: ../CitibikeApiProducer
      dockerfile: Dockerfile-station-status
    depends_on:
      - kafka
      - zookeeper-seed
    networks:
      - streaming-data-internal
    environment:
      - PRODUCER_URL=https://gbfs.citibikenyc.com/gbfs/en/station_status.json
      - PRODUCER_TOPIC=e2e_station_status
      - PRODUCER_PRODUCERID=e2e_producer_station_status
      - PRODUCER_CRON=*/3 * * * * *

  station-san-francisco-producer:
    build:
      context: ../CitibikeApiProducer
      dockerfile: Dockerfile-station-san-francisco
    depends_on:
      - kafka
      - zookeeper-seed
    networks:
      - streaming-data-internal
    environment:
      - PRODUCER_URL=https://api.citybik.es/v2/networks/ford-gobike
      - PRODUCER_TOPIC=e2e_station_data_sf
      - PRODUCER_PRODUCERID=e2e_producer_station-san_francisco
      - PRODUCER_CRON=*/3 * * * * *

  station-marseille-producer:
    build:
      context: ../CitibikeApiProducer
      dockerfile: Dockerfile-station-marseille
    depends_on:
      - kafka
      - zookeeper-seed
    networks:
      - streaming-data-internal
    environment:
      - PRODUCER_URL=https://api.citybik.es/v2/networks/le-velo
      - PRODUCER_TOPIC=e2e_station_data_marseille
      - PRODUCER_PRODUCERID=e2e_producer_station-marseille
      - PRODUCER_CRON=*/3 * * * * *

